Aland
utopia-knights-tour/aaa-airlines-lambda-getflights pull request #1
Opened 2020-04-17 15:27 UTC by alandchang-smoothstack

2020-04-17 19:28 UTC, AlexChavez235 requested changes

2020-04-17 19:28 UTC, AlexChavez235 commented on src/main/java/GetFlights.java
> +			e.printStackTrace();
Maybe throw some kind of runtime exception here instead that you can make to an error status code in API Gateway?

2020-04-18 22:04 UTC, allistergg requested changes

2020-04-18 22:04 UTC, allistergg commented on src/main/java/entity/Flight.java
> +	private Double cost;
maybe try BigDecimal for money

2020-04-20 02:18 UTC, AlexChavez235 approved these changes

2020-04-20 16:42 UTC, AlexChavez235 approved these changes

2020-04-20 16:58 UTC, allistergg approved these changes

2020-04-20 17:05 UTC, merged